# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49a1c0d9998b5f1d75f1443336253897837d783384c3e5021a22a82f981d7462de8c6862b7a4dbe46165d73ddf322cb31b49e57b0580416014b68e2050253f2

test:
  secret_key_base: 3a1c74ccfafd4b83a795f40883625e913cfe9d8e942d64405bbc1333bf8b1bb7cf6c5a21cca195f019a98e6d21ff51be4e492ba85c116a418804f74e9820525e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
